name: Run tests and upload coverage

on:
  workflow_dispatch:
#  pull_request:
#    types: [opened, synchronize, edited]
#  push:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install pytest pytest-cov coverage codecov

      - name: Run tests with coverage
        run: |
          PYTHONPATH=. pytest --cov=pythonuef_github_lib_template --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests
          name: codecov-py